### ISSUE TITLE
Encrypting/Decrypting Messages

### ISSUE THREAD

**Issue by noahcoomer** [noahcoomer/BlockchainPKI#11]
In client.py, I think that the functions encrypt_public_key() and decrypt_private_key() seem to be mixed up or misnamed. A client would encrypt a message with a public key, then decrypt it with a private key. I also suggest renaming them to encrypt_message() and decrypt_message().

**Comment by Boellis** [comment]
Fixed this. Thanks for the suggestion and direction!
