### ISSUE TITLE
Hashing functions in Block and Transaction

### ISSUE THREAD

**Issue by noahcoomer** [noahcoomer/BlockchainPKI#30]
`compute_merkle_root()` in `Block` and `__hash__()` in both `Block` and `Transaction` should return sha256 hashed strings

**Comment by marshalhayes** [comment]
Is this finished? See https://github.com/noahcoomer/BlockchainPKI/blob/4df5987e4d3a9131ad8048350adc22cc3d143d6c/src/transaction.py#L58

**Comment by noahcoomer** [comment]
Yep, this was fixed with the `__str__` magic function and the function mentioned above.
